// ==========================================
// VARIÁVEIS GLOBAIS E UTILITÁRIOS
// ==========================================
const $ = id => document.getElementById(id);
const hide = id => $(id).classList.add('hidden');
const show = id => $(id).classList.remove('hidden');
const sleep = ms => new Promise(r => setTimeout(r, ms));
const toRoman = n => ['', 'I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX', 'X'][n] || n;

let activeArtifactsCamp = [], activeArtifactsRogue = [], stats = { maxLevel: 1, wins: 0, losses: 0 }, rosterMemory = [], deployedRoster = [], unlockedBeasts = [], shopItems = [], game, renderer, lastState = null;
let reliquaryViewMode = 'camp';

const getActiveArtifacts = () => { return (game && game.isRoguelite) ? activeArtifactsRogue : activeArtifactsCamp; };

// ==========================================
// DADOS DO JOGO (TERRENOS, TAGS E MAGIAS)
// ==========================================
const TERRAINS = { PLAINS: { id: 'PLAINS', name: 'Planície', cost: 1, def: 0.00, color: '#3a5a2a', icon: '' }, FOREST: { id: 'FOREST', name: 'Floresta', cost: 2, def: 0.20, color: '#23411b', icon: '🌲' }, MOUNTAIN: { id: 'MOUNTAIN', name: 'Montanha', cost: 3, def: 0.40, color: '#4a554a', icon: '⛰️' }, WATER: { id: 'WATER', name: 'Água', cost: 2, def: -0.15, color: '#1c4568', icon: '🌊' }, SNOW: { id: 'SNOW', name: 'Neve', cost: 2, def: -0.15, color: '#b8cad4', icon: '❄️' }, DESERT: { id: 'DESERT', name: 'Deserto', cost: 2, def: 0.00, color: '#d2b48c', icon: '🏜️' }, VILLAGE: { id: 'VILLAGE', name: 'Vila', cost: 1, def: 0.20, color: '#8a753c', icon: '🏘️' }, CASTLE: { id: 'CASTLE', name: 'Castelo', cost: 1, def: 0.60, color: '#505860', icon: '🏰' } };

const TAGS = {
    FIRE: { name: 'Ígneo', col: '#e67e22', req: 3, desc: '(3) Causa 20% de dano em área.' },
    SILVESTRE: { name: 'Silvestre', col: '#27ae60', req: 3, desc: '(3) Cura +5 HP e 15% chance de Atordoar.' },
    ABYSSAL: { name: 'Abissal', col: '#3498db', req: 3, desc: '(3) 20% de Esquiva e sem atraso de terreno.' },
    ROCK: { name: 'Rochoso', col: '#95a5a6', req: 3, desc: '(3) +30% Defesa Base (Máx 60%).' },
    SAND: { name: 'Arenoso', col: '#f1c40f', req: 3, desc: '(3) Ganham "Bater e Correr".' },
    ICE: { name: 'Gélido', col: '#00ffff', req: 3, desc: '(3) Ataques reduzem MP do alvo em 2.' },
    UMBRAL: { name: 'Umbral', col: '#8e44ad', req: 3, desc: '(3) Ganham 25% de Roubo de Vida.' },
    CELESTIAL: { name: 'Celestial', col: '#fffbc2', req: 3, desc: '(3) Curam 10 HP e removem debuffs em volta.' },
    PRIMAL: { name: 'Primal', col: '#e74c3c', req: 2, desc: '(2) Ganham +1 de Ataque por turno vivo.' },
    WING: { name: 'Alado', col: '#ecf0f1', req: 2, desc: '(2) Custo 1 em tudo e sem defesa negativa.' },
    VENOM: { name: 'Venenoso', col: '#9b59b6', req: 2, desc: '(2) Veneno tira 10 HP e 100% de chance.' },
    STALKER: { name: 'Rastreador', col: '#d35400', req: 3, desc: '(3) Flanquear inimigo ignora def e dobra dano.' },
    CARAPACE: { name: 'Carapaça', col: '#7f8c8d', req: 2, desc: '(2) Refletem 10% do dano recebido.' },
    MYSTIC: { name: 'Místico', col: '#9b59b6', req: 2, desc: '(2) 30% chance de resetar MP (Ação Extra).' }
};

const MANA_TYPES = { FIRE: { icon: '🔥', col: '#e67e22', name: 'Fogo' }, SILVESTRE: { icon: '🌿', col: '#27ae60', name: 'Vida' }, ABYSSAL: { icon: '💧', col: '#3498db', name: 'Abissal' }, ROCK: { icon: '⛏️', col: '#95a5a6', name: 'Terra' }, SAND: { icon: '🌪️', col: '#f1c40f', name: 'Areia' }, ICE: { icon: '❄️', col: '#00ffff', name: 'Gelo' }, UMBRAL: { icon: '🌑', col: '#8e44ad', name: 'Umbra' }, CELESTIAL: { icon: '✨', col: '#fffbc2', name: 'Luz' }, PRIMAL: { icon: '🦴', col: '#e74c3c', name: 'Primal' }, WING: { icon: '🪶', col: '#ecf0f1', name: 'Vento' }, VENOM: { icon: '☠️', col: '#9b59b6', name: 'Veneno' }, STALKER: { icon: '👁️', col: '#d35400', name: 'Sombra' }, CARAPACE: { icon: '🛡️', col: '#7f8c8d', name: 'Pedra' }, MYSTIC: { icon: '🔮', col: '#9b59b6', name: 'Arcano' } };

const SPELLS = [
    { id: 'sl_ember', name: 'Centelha', icon: '🔥', level: 1, tags: ['FIRE'], type: 'atk', range: 2, cost: { FIRE: 1 }, desc: 'Causa 10 de dano de fogo.', effect: async (g, c, t) => { t.hp -= 10; showPopup("🔥 -10", t, '#e67e22'); addLog(`🔥 ${c.name} lançou Centelha em ${t.name}!`, '#e67e22'); if (t.hp <= 0) g.handleDeath(t, c); g.checkWin(); return true; } },
    { id: 'sl_heal', name: 'Cura Menor', icon: '💚', level: 1, tags: ['SILVESTRE'], type: 'def', range: 3, cost: { SILVESTRE: 1 }, desc: 'Cura 20 HP de um aliado.', effect: async (g, c, t) => { let h = Math.min(t.maxHp - t.hp, 20); t.hp += h; showPopup(`+${h}`, t, '#2ecc71'); addLog(`💚 ${c.name} curou ${t.name}!`, '#27ae60'); return true; } },
    { id: 'sl_tidal', name: 'Onda Menor', icon: '💧', level: 1, tags: ['ABYSSAL'], type: 'atk', range: 0, cost: { ABYSSAL: 1 }, desc: 'Causa 3 de dano em inimigos adjacentes.', effect: async (g, c, t) => { let n = Hex.getNeighbors(c.q, c.r); let hit = 0; for (let nb of n) { let u = g.getUnitAt(nb.q, nb.r); if (u && u.faction !== c.faction) { u.hp -= 3; showPopup("💧 -3", u, '#3498db'); hit++; if (u.hp <= 0) g.handleDeath(u, c); } } addLog(`💧 ${c.name} lançou Onda Menor!`, '#3498db'); g.checkWin(); return hit > 0 || true; } },
    { id: 'sl_rock_wall', name: 'Pele de Pedra', icon: '🪨', level: 1, tags: ['ROCK', 'CARAPACE'], type: 'def', range: 3, cost: { ROCK: 1 }, desc: 'Um aliado ganha +30% Defesa base por 1 turno.', effect: async (g, c, t) => { t.status = 'shielded'; showPopup("🪨 Escudo", t, '#95a5a6'); addLog(`🪨 ${t.name} ganhou Pele de Pedra!`, '#95a5a6'); return true; } },
    { id: 'sl_venom_spit', name: 'Cuspe Venenoso', icon: '☠️', level: 1, tags: ['VENOM'], type: 'atk', range: 2, cost: { VENOM: 1 }, desc: 'Envenena 1 inimigo.', effect: async (g, c, t) => { t.status = 'poison'; showPopup("☠️ Veneno", t, '#9b59b6'); addLog(`☠️ ${c.name} envenenou ${t.name}!`, '#9b59b6'); return true; } },
    { id: 'sl_gust', name: 'Rajada', icon: '🪶', level: 1, tags: ['WING'], type: 'def', range: 3, cost: { WING: 1 }, desc: 'Um aliado ganha +2 de Movimento neste turno.', effect: async (g, c, t) => { t.mp += 2; showPopup("+2 Mov", t, '#ecf0f1'); addLog(`🪶 ${t.name} ganhou Rajada!`, '#ecf0f1'); return true; } },
    { id: 'sl_sand_throw', name: 'Poeira Ofuscante', icon: '🌪️', level: 1, tags: ['SAND'], type: 'atk', range: 2, cost: { SAND: 1 }, desc: 'Causa 3 de dano e reduz 1 MP.', effect: async (g, c, t) => { t.hp -= 3; t.mp = Math.max(0, t.mp - 1); showPopup("🌪️ -3", t, '#f1c40f'); addLog(`🌪️ ${c.name} lançou Poeira em ${t.name}!`, '#f1c40f'); if (t.hp <= 0) g.handleDeath(t, c); g.checkWin(); return true; } },
    { id: 'sl_ice_shard', name: 'Estilhaço de Gelo', icon: '🧊', level: 1, tags: ['ICE'], type: 'atk', range: 3, cost: { ICE: 1 }, desc: 'Causa 6 de dano de gelo.', effect: async (g, c, t) => { t.hp -= 6; showPopup("🧊 -6", t, '#00ffff'); addLog(`🧊 ${c.name} atirou Estilhaço!`, '#00ffff'); if (t.hp <= 0) g.handleDeath(t, c); g.checkWin(); return true; } },
    { id: 'sl_dark_touch', name: 'Toque Sombrio', icon: '🌑', level: 1, tags: ['UMBRAL'], type: 'atk', range: 1, cost: { UMBRAL: 1 }, desc: 'Drena 6 HP de um inimigo adjacente.', effect: async (g, c, t) => { t.hp -= 6; c.hp = Math.min(c.maxHp, c.hp + 6); showPopup("🌑 -6", t, '#8e44ad'); showPopup("🌑 +6", c, '#8e44ad'); addLog(`🌑 ${c.name} drenou vida!`, '#8e44ad'); if (t.hp <= 0) g.handleDeath(t, c); g.checkWin(); return true; } },
    { id: 'sl_guiding_light', name: 'Luz Guia', icon: '🌟', level: 1, tags: ['CELESTIAL'], type: 'def', range: 0, cost: { CELESTIAL: 1 }, desc: 'Cura 10 HP de aliados próximos.', effect: async (g, c, t) => { let hit = false; Hex.getNeighbors(c.q, c.r).forEach(n => { let u = g.getUnitAt(n.q, n.r); if (u && u.faction === c.faction) { u.status = null; let h = Math.min(u.maxHp - u.hp, 10); u.hp += h; showPopup(`🌟 +${h}`, u, '#fffbc2'); hit = true; } }); if (!hit) { let h = Math.min(c.maxHp - c.hp, 10); c.hp += h; c.status = null; showPopup(`🌟 +${h}`, c, '#fffbc2'); } return true; } },
    { id: 'sl_savage_cry', name: 'Grito Selvagem', icon: '🐺', level: 1, tags: ['PRIMAL'], type: 'def', range: 0, cost: { PRIMAL: 1 }, desc: 'O Líder ganha +5 ATK neste turno.', effect: async (g, c, t) => { c.furyAtk = (c.furyAtk || 0) + 5; showPopup("+5 ATK", c, '#e74c3c'); return true; } },
    { id: 'sl_hunters_mark', name: 'Marca do Caçador', icon: '🎯', level: 1, tags: ['STALKER'], type: 'atk', range: 3, cost: { STALKER: 1 }, desc: 'Causa 6 de dano verdadeiro.', effect: async (g, c, t) => { t.hp -= 6; showPopup("🎯 -6", t, '#d35400'); if (t.hp <= 0) g.handleDeath(t, c); g.checkWin(); return true; } },
    { id: 'sl_arcane_dart', name: 'Dardo Arcano', icon: '🔮', level: 1, tags: ['MYSTIC'], type: 'atk', range: 3, cost: { MYSTIC: 1 }, desc: 'Causa 8 de dano.', effect: async (g, c, t) => { t.hp -= 8; showPopup("🔮 -8", t, '#9b59b6'); if (t.hp <= 0) g.handleDeath(t, c); g.checkWin(); return true; } },

    // Level 2, 3, 4, 5
    { id: 'sl_tornado', name: 'Tornado', icon: '🌪️', level: 2, tags: ['WING'], type: 'atk', range: 99, cost: { WING: 2 }, desc: 'Causa 12 de dano a todos os inimigos.', effect: async (g, c, t) => { g.units.filter(u => u.faction !== c.faction).forEach(u => { u.hp -= 12; showPopup("🌪️ -12", u, '#ecf0f1'); if (u.hp <= 0) g.handleDeath(u, c); }); addLog(`🌪️ Um Tornado varreu o mapa!`, '#ecf0f1'); g.checkWin(); return true; } },
    { id: 'sl_thorn_armor', name: 'Armadura de Espinhos', icon: '🌵', level: 2, tags: ['CARAPACE'], type: 'def', range: 3, cost: { CARAPACE: 2 }, desc: 'Dá Carapaça (+Def e Reflete Dano) a um aliado.', effect: async (g, c, t) => { if (!t.abilities.includes('carapace')) t.abilities.push('carapace'); t.status = 'shielded'; showPopup("🌵 Espinhos", t, '#7f8c8d'); return true; } },
    { id: 'sl_assassinate', name: 'Ataque Furtivo', icon: '🗡️', level: 2, tags: ['STALKER'], type: 'atk', range: 4, cost: { STALKER: 2 }, desc: 'Causa 22 de dano massivo num inimigo.', effect: async (g, c, t) => { t.hp -= 22; showPopup("🗡️ -22", t, '#d35400'); if (t.hp <= 0) g.handleDeath(t, c); g.checkWin(); return true; } },
    { id: 'sl_quicksand', name: 'Dunas Movediças', icon: '🏜️', level: 3, tags: ['SAND'], type: 'atk', range: 99, cost: { SAND: 3 }, desc: 'Prende (Amarrar) TODOS os inimigos e causa 8 dano.', effect: async (g, c, t) => { g.units.filter(u => u.faction !== c.faction).forEach(u => { u.status = 'bind'; u.hp -= 8; showPopup("🏜️ Preso!", u, '#f1c40f'); if (u.hp <= 0) g.handleDeath(u, c); }); g.checkWin(); return true; } },
    { id: 'sl_fireball', name: 'Bola de Fogo', icon: '🌋', level: 2, tags: ['FIRE'], type: 'atk', range: 3, cost: { FIRE: 2 }, desc: 'Causa 18 de dano de fogo.', effect: async (g, c, t) => { t.hp -= 18; showPopup("🌋 -18", t, '#e67e22'); if (t.hp <= 0) g.handleDeath(t, c); g.checkWin(); return true; } },
    { id: 'sl_regen', name: 'Regeneração', icon: '🌿', level: 2, tags: ['SILVESTRE'], type: 'def', range: 99, cost: { SILVESTRE: 2 }, desc: 'Cura 15 HP de todas as unidades aliadas.', effect: async (g, c, t) => { g.units.filter(u => u.faction === c.faction).forEach(u => { let h = Math.min(u.maxHp - u.hp, 15); u.hp += h; if (h > 0) showPopup(`+${h}`, u, '#27ae60'); }); return true; } },
    { id: 'sl_freeze', name: 'Toque Glacial', icon: '❄️', level: 2, tags: ['ICE'], type: 'atk', range: 2, cost: { ICE: 2 }, desc: 'Atordoa 1 inimigo por 1 turno completo.', effect: async (g, c, t) => { t.status = 'stun'; showPopup("❄️ Congelado", t, '#00ffff'); return true; } },
    { id: 'sl_shadow_step', name: 'Passo Sombrio', icon: '🌑', level: 2, tags: ['UMBRAL', 'STALKER'], type: 'atk', range: 99, cost: { UMBRAL: 2 }, desc: 'Teleporta o Líder para perto de um alvo fraco.', effect: async (g, c, t) => { let ws = g.units.filter(u => u.faction !== c.faction && u.hp <= u.maxHp * 0.5).sort((a, b) => a.hp - b.hp); if (!ws.length) { showMessage("Nenhum alvo fraco!", "#8e44ad"); return false; } let tgt = ws[0]; let nb = Hex.getNeighbors(tgt.q, tgt.r).find(n => g.map.has(`${n.q},${n.r}`) && !g.getUnitAt(n.q, n.r)); if (!nb) { showMessage("Sem espaço!", "#8e44ad"); return false; } c.q = nb.q; c.r = nb.r; c.vq = nb.q; c.vr = nb.r; renderer.centerOn(nb.q, nb.r); showPopup("🌑 Teleporte", c, '#8e44ad'); return true; } },
    { id: 'sl_primal_rage', name: 'Fúria Primal', icon: '🦴', level: 2, tags: ['PRIMAL'], type: 'def', range: 99, cost: { PRIMAL: 2 }, desc: 'Concede +8 ATK a aliados neste turno.', effect: async (g, c, t) => { g.units.filter(u => u.faction === c.faction && !u.isLeader).forEach(u => { u.furyAtk = (u.furyAtk || 0) + 8; showPopup("+8 ATK", u, '#e74c3c'); }); return true; } },
    { id: 'sl_light_beam', name: 'Raio de Luz', icon: '✨', level: 2, tags: ['CELESTIAL'], type: 'def', range: 0, cost: { CELESTIAL: 2 }, desc: 'Remove debuffs de aliados próximos e cura 10 HP.', effect: async (g, c, t) => { Hex.getNeighbors(c.q, c.r).forEach(n => { let u = g.getUnitAt(n.q, n.r); if (u && u.faction === c.faction) { u.status = null; let h = Math.min(u.maxHp - u.hp, 10); u.hp += h; showPopup(`✨+${h}`, u, '#fffbc2'); } }); return true; } },
    { id: 'sl_sandstorm', name: 'Tempestade de Areia', icon: '🌪️', level: 2, tags: ['SAND'], type: 'atk', range: 99, cost: { SAND: 2 }, desc: 'Reduz MP de todos os inimigos em 2.', effect: async (g, c, t) => { g.units.filter(u => u.faction !== c.faction).forEach(u => { u.mp = Math.max(0, u.mp - 2); showPopup("-2 MP", u, '#f1c40f'); }); return true; } },
    { id: 'sl_inferno', name: 'Inferno', icon: '☄️', level: 3, tags: ['FIRE'], type: 'atk', range: 99, cost: { FIRE: 3 }, desc: 'Causa 12 de dano a TODOS os inimigos.', effect: async (g, c, t) => { let enemies = g.units.filter(u => u.faction !== c.faction); enemies.forEach(u => { u.hp -= 12; showPopup("☄️ -12", u, '#e67e22'); if (u.hp <= 0) g.handleDeath(u, c); }); g.checkWin(); return true; } },
    { id: 'sl_nature_shield', name: 'Escudo Natural', icon: '🍃', level: 3, tags: ['SILVESTRE'], type: 'def', range: 0, cost: { SILVESTRE: 3 }, desc: 'Cura 30 HP do Líder e remove todos debuffs.', effect: async (g, c, t) => { let h = Math.min(c.maxHp - c.hp, 30); c.hp += h; c.status = null; showPopup(`🍃+${h}`, c, '#27ae60'); return true; } },
    { id: 'sl_blizzard', name: 'Nevasca', icon: '🌨️', level: 3, tags: ['ICE'], type: 'atk', range: 99, cost: { ICE: 3 }, desc: 'Causa 10 de dano e Atrasa 2 MP.', effect: async (g, c, t) => { g.units.filter(u => u.faction !== c.faction).forEach(u => { u.hp -= 10; u.mp = Math.max(0, u.mp - 2); showPopup("🌨️ -10", u, '#00ffff'); if (u.hp <= 0) g.handleDeath(u, c); }); g.checkWin(); return true; } },
    { id: 'sl_void_drain', name: 'Drenagem do Vazio', icon: '🌀', level: 3, tags: ['UMBRAL'], type: 'atk', range: 3, cost: { UMBRAL: 3 }, desc: 'Drena 15 HP de um alvo.', effect: async (g, c, t) => { t.hp -= 15; c.hp = Math.min(c.maxHp, c.hp + 15); showPopup("🌀 -15", t, '#8e44ad'); showPopup("🌀 +15", c, '#8e44ad'); if (t.hp <= 0) g.handleDeath(t, c); g.checkWin(); return true; } },
    { id: 'sl_stone_rain', name: 'Chuva de Pedras', icon: '🪨', level: 3, tags: ['ROCK', 'CARAPACE'], type: 'atk', range: 0, cost: { ROCK: 3 }, desc: 'Causa 8 de dano a inimigos adjacentes.', effect: async (g, c, t) => { let hit = false; Hex.getNeighbors(c.q, c.r).forEach(n => { let u = g.getUnitAt(n.q, n.r); if (u && u.faction !== c.faction) { u.hp -= 8; showPopup("🪨 -8", u, '#95a5a6'); hit = true; if (u.hp <= 0) g.handleDeath(u, c); } }); g.checkWin(); return true; } },
    { id: 'sl_mass_venom', name: 'Praga', icon: '💀', level: 3, tags: ['VENOM'], type: 'atk', range: 99, cost: { VENOM: 3 }, desc: 'Envenena TODOS os inimigos.', effect: async (g, c, t) => { g.units.filter(u => u.faction !== c.faction).forEach(u => { u.status = 'poison'; showPopup("💀 Praga", u, '#9b59b6'); }); return true; } },
    { id: 'sl_storm_wing', name: 'Tempestade Alada', icon: '🌩️', level: 3, tags: ['WING'], type: 'atk', range: 4, cost: { WING: 3 }, desc: 'Todas as unidades ALADAS atacam o alvo.', effect: async (g, c, t) => { let wings = g.units.filter(u => u.faction === c.faction && u.tags.includes('WING') && u.hp > 0); if (!wings.length) return false; for (let w of wings) { if (t.hp > 0) { t.hp -= w.atk; showPopup(`🌩️ -${w.atk}`, t, '#ecf0f1'); if (t.hp <= 0) g.handleDeath(t, w); } } g.checkWin(); return true; } },
    { id: 'sl_meteor', name: 'Meteorito', icon: '💫', level: 4, tags: ['FIRE'], type: 'atk', range: 99, cost: { FIRE: 3, ROCK: 1 }, desc: 'Causa 30 de dano em área a todos os inimigos.', effect: async (g, c, t) => { g.units.filter(u => u.faction !== c.faction).forEach(u => { u.hp -= 30; showPopup("💫 -30", u, '#e67e22'); if (u.hp <= 0) g.handleDeath(u, c); }); g.checkWin(); return true; } },
    { id: 'sl_resurrection', name: 'Ressurreição', icon: '💛', level: 4, tags: ['CELESTIAL', 'SILVESTRE'], type: 'def', range: 1, cost: { CELESTIAL: 2, SILVESTRE: 2 }, desc: 'Revive a última fera morta num espaço adjacente.', effect: async (g, c, t, cH) => { if (!g.lastDeadAlly) return false; if (g.getUnitAt(cH.q, cH.r)) return false; let d = g.lastDeadAlly; d.q = cH.q; d.r = cH.r; d.vq = cH.q; d.vr = cH.r; d.hp = Math.floor(d.maxHp * 0.5); d.hasAttacked = false; d.status = null; g.units.push(d); g.lastDeadAlly = null; showPopup("💛 Revivido!", d, '#fffbc2'); return true; } },
    { id: 'sl_mind_control', name: 'Controle Mental', icon: '🧠', level: 4, tags: ['MYSTIC'], type: 'atk', range: 3, cost: { MYSTIC: 3 }, desc: 'Converte um inimigo temporariamente por 2 turnos.', effect: async (g, c, t) => { if (t.isBoss) return false; t._origFaction = t.faction; t.faction = 1; t._mcDuration = 2; t.mp = t.maxMp; t.hasAttacked = false; t.status = null; showPopup("🧠 Controlado!", t, '#9b59b6'); return true; } },
    { id: 'sl_tidal_wave', name: 'Maré Gigante', icon: '🌊', level: 4, tags: ['ABYSSAL'], type: 'atk', range: 99, cost: { ABYSSAL: 3 }, desc: 'Causa 20 de dano a todos os inimigos e empurra.', effect: async (g, c, t) => { g.units.filter(u => u.faction !== c.faction).forEach(u => { u.hp -= 20; u.mp = Math.max(0, u.mp - 3); showPopup("🌊 -20", u, '#3498db'); if (u.hp <= 0) g.handleDeath(u, c); }); g.checkWin(); return true; } },
    { id: 'sl_apocalypse', name: 'Apocalipse', icon: '🌠', level: 5, tags: ['FIRE'], type: 'atk', range: 99, cost: { FIRE: 4, PRIMAL: 1 }, desc: 'Causa 40 de dano verdadeiro a todos.', effect: async (g, c, t) => { g.units.filter(u => u.faction !== c.faction).forEach(u => { u.hp -= 40; showPopup("🌠 -40", u, '#e74c3c'); if (u.hp <= 0) g.handleDeath(u, c); }); g.checkWin(); return true; } },
    { id: 'sl_phoenix_rebirth', name: 'Renascimento Fênix', icon: '🔱', level: 5, tags: ['CELESTIAL', 'FIRE'], type: 'def', range: 99, cost: { CELESTIAL: 3, FIRE: 2 }, desc: 'Cura TODOS os aliados para HP Máx.', effect: async (g, c, t) => { g.units.filter(u => u.faction === c.faction).forEach(u => { u.hp = u.maxHp; u.status = null; showPopup("🔱 PLENO", u, '#fffbc2'); }); return true; } },
    { id: 'sl_world_freeze', name: 'Congelamento Mundial', icon: '🧊', level: 5, tags: ['ICE'], type: 'atk', range: 99, cost: { ICE: 4 }, desc: 'Atordoa TODOS os inimigos por 1 turno e causa 15 dano.', effect: async (g, c, t) => { g.units.filter(u => u.faction !== c.faction).forEach(u => { u.status = 'stun'; u.hp -= 15; showPopup("🧊 CONGELADO", u, '#00ffff'); if (u.hp <= 0) g.handleDeath(u, c); }); g.checkWin(); return true; } },
    { id: 'sl_soul_harvest', name: 'Colheita de Almas', icon: '⚡', level: 5, tags: ['UMBRAL', 'VENOM'], type: 'atk', range: 99, cost: { UMBRAL: 3, VENOM: 2 }, desc: 'Drena 25% do HP atual de TODOS inimigos.', effect: async (g, c, t) => { let total = 0; g.units.filter(u => u.faction !== c.faction && u.hp > 0).forEach(u => { let d = Math.floor(u.hp * 0.25); u.hp -= d; total += d; showPopup(`⚡ -${d}`, u, '#8e44ad'); if (u.hp <= 0) g.handleDeath(u, c); }); c.hp = Math.min(c.maxHp, c.hp + total); showPopup(`⚡ +${total}`, c, '#8e44ad'); g.checkWin(); return true; } },

    //Spells de Líder
    { id: 'sl_mordida_vamp', name: 'Mordida Vampírica', icon: '🦇', cost: { 'UMBRAL': 2 }, level: 1, type: 'atk', range: 1, tags: ['UMBRAL'], desc: 'Causa dano e cura o Lord Vampiro.', effect: async (game, caster, target) => { if (!target) return false; let dmg = 20; target.hp -= dmg; caster.hp = Math.min(caster.maxHp, caster.hp + dmg); showPopup("-20 HP", target, '#fff'); showPopup("+20 HP", caster, '#2ecc71'); if (target.hp <= 0) game.handleDeath(target, caster); return true; } },
    { id: 'sl_bencao_paladina', name: 'Bênção Divina', icon: '✨', cost: { 'CELESTIAL': 2 }, level: 1, type: 'def', range: 2, tags: ['CELESTIAL'], desc: 'Cura um aliado em 40 HP e remove debuffs.', effect: async (game, caster, target) => { if (!target || target.faction !== 1) return false; target.hp = Math.min(target.maxHp, target.hp + 40); target.status = null; showPopup("+40 HP", target, '#f1c40f'); return true; } },
    { id: 'sl_bombardeio', name: 'Bombardeio Naval', icon: '💣', cost: { 'ABYSSAL': 3 }, level: 1, type: 'atk', range: 3, tags: ['ABYSSAL'], desc: 'Causa 25 de dano a um inimigo distante.', effect: async (game, caster, target) => { if (!target) return false; target.hp -= 25; showPopup("-25 💣", target, '#e74c3c'); if (target.hp <= 0) game.handleDeath(target, caster); return true; } },
    { id: 'sl_tiro_preciso', name: 'Tiro Preciso', icon: '🏹', cost: { 'SILVESTRE': 2 }, level: 1, type: 'atk', range: 4, tags: ['SILVESTRE'], desc: 'Causa 30 de dano perfurante de longa distância.', effect: async (game, caster, target) => { if (!target) return false; target.hp -= 30; showPopup("-30 🏹", target, '#e74c3c'); if (target.hp <= 0) game.handleDeath(target, caster); return true; } },
    { id: 'sl_bola_fogo', name: 'Bola de Fogo', icon: '🔥', cost: { 'FIRE': 2 }, level: 1, type: 'atk', range: 2, tags: ['FIRE'], desc: 'Causa 25 de dano e queima o inimigo.', effect: async (game, caster, target) => { if (!target) return false; target.hp -= 25; target.status = 'burn'; showPopup("-25 🔥", target, '#e67e22'); if (target.hp <= 0) game.handleDeath(target, caster); return true; } },
    { id: 'sl_grito_orc', name: 'Grito de Guerra', icon: '📯', cost: { 'PRIMAL': 2 }, level: 1, type: 'def', range: 0, tags: ['PRIMAL'], desc: 'Concede Ação Extra para o Chefe Orc.', effect: async (game, caster) => { caster.hasAttacked = false; caster.mp = caster.maxMp; showPopup("Ação Extra!", caster, '#e74c3c'); return true; } },
    { id: 'sl_erguer_esq', name: 'Erguer Esqueleto', icon: '💀', cost: { 'UMBRAL': 2 }, level: 1, type: 'def', range: 1, tags: ['UMBRAL'], desc: 'Invoca um Esqueleto para lutar por você.', effect: async (game, caster, target, targetHex) => { if (target) return false; let d = new Unit({ q: targetHex.q, r: targetHex.r, faction: 1, name: "Esqueleto", emoji: "💀", hp: 25, maxHp: 25, mp: 3, maxMp: 3, atk: 8, range: 1, abilities: [], tags: ['UMBRAL', 'MYSTIC'], isNew: false }); game.units.push(d); showPopup("Erguido!", d, '#8e44ad'); return true; } },
    { id: 'sl_explosao_arcana', name: 'Explosão Arcana', icon: '🎇', cost: { 'MYSTIC': 2 }, level: 1, type: 'atk', range: 2, tags: ['MYSTIC'], desc: 'Dano mágico alto no alvo (35 Dano).', effect: async (game, caster, target) => { if (!target) return false; target.hp -= 35; showPopup("-35 🎇", target, '#9b59b6'); if (target.hp <= 0) game.handleDeath(target, caster); return true; } },
    { id: 'sl_forma_urso', name: 'Postura do Urso', icon: '🐻', cost: {}, level: 1, type: 'def', range: 0, tags: ['PRIMAL'], desc: 'Gratuito. Alterna para Urso: Alcance 1, recupera a Defesa base e ganha +20 HP Máx.', effect: async (game, caster) => { if (caster.emoji === '🐻') return false; if (caster.emoji === '🦅') { caster.maxHp -= 20; caster.hp = Math.min(caster.maxHp, caster.hp); caster.abilities = caster.abilities.filter(a => a !== 'pierce'); } caster.emoji = '🐻'; caster.range = 1; caster.maxHp += 20; caster.hp += 20; showPopup("Forma Urso!", caster, '#f39c12'); return true; } },
    { id: 'sl_forma_falcao', name: 'Postura do Falcão', icon: '🦅', cost: {}, level: 1, type: 'def', range: 0, tags: ['PRIMAL'], desc: 'Gratuito. Alterna para Falcão: Perde a Defesa do Urso, ganha 3 de Alcance e ataques Perfurantes.', effect: async (game, caster) => { if (caster.emoji === '🦅') return false; if (caster.emoji === '🐻') { caster.maxHp -= 20; caster.hp = Math.min(caster.maxHp, caster.hp); } caster.emoji = '🦅'; caster.range = 3; if (!caster.abilities.includes('pierce')) caster.abilities.push('pierce'); showPopup("Forma Falcão!", caster, '#3498db'); return true; } },
    { id: 'sl_execucao', name: 'Execução', icon: '🪓', cost: { 'UMBRAL': 2 }, level: 1, type: 'atk', range: 1, tags: ['UMBRAL'], desc: 'Ataque fatal. Se o alvo morrer, você recupera seu turno e movimento.', effect: async (game, caster, target) => { if (!target) return false; caster._isExecuting = true; await game.executeCombat(caster, target); caster._isExecuting = false; return true; } },
    { id: 'sl_evocar_dragao', name: 'Evocar Dragão Ígneo', icon: '🐉', cost: { 'MYSTIC': 3, 'FIRE': 2 }, level: 2, type: 'def', range: 1, tags: ['MYSTIC'], desc: 'Invoca um Dragão no campo que dura até o fim da batalha.', effect: async (game, caster, target, targetHex) => { if (target) return false; let d = new Unit({ q: targetHex.q, r: targetHex.r, faction: 1, name: "Dragão Evocado", emoji: "🐉", hp: 60, maxHp: 60, mp: 4, maxMp: 4, atk: 18, range: 2, abilities: ['burn'], tags: ['FIRE'], isNew: false }); game.units.push(d); showPopup("Invocado!", d, '#e74c3c'); return true; } },
    { id: 'sl_evocar_lobo', name: 'Evocar Lobo de Mana', icon: '🐺', cost: { 'MYSTIC': 2 }, level: 1, type: 'def', range: 1, tags: ['MYSTIC'], desc: 'Invoca um Lobo espiritual (Fera) para lutar ao seu lado.', effect: async (game, caster, target, targetHex) => { if (target) return false; let d = new Unit({ q: targetHex.q, r: targetHex.r, faction: 1, name: "Lobo de Mana", emoji: "🐺", hp: 35, maxHp: 35, mp: 4, maxMp: 4, atk: 12, range: 1, abilities: ['dodge'], tags: ['MYSTIC'], isNew: false }); game.units.push(d); showPopup("Invocado!", d, '#9b59b6'); return true; } },
    { id: 'sl_evocar_golem', name: 'Evocar Golem de Pedra', icon: '🪨', cost: { 'MYSTIC': 2, 'ROCK': 2 }, level: 1, type: 'def', range: 1, tags: ['MYSTIC'], desc: 'Invoca um Golem resistente de Pedra.', effect: async (game, caster, target, targetHex) => { if (target) return false; let d = new Unit({ q: targetHex.q, r: targetHex.r, faction: 1, name: "Golem de Pedra", emoji: "🪨", hp: 80, maxHp: 80, mp: 2, maxMp: 2, atk: 10, range: 1, abilities: ['carapace'], tags: ['ROCK'], isNew: false }); game.units.push(d); showPopup("Invocado!", d, '#95a5a6'); return true; } },
    { id: 'sl_cancao_sereia', name: 'Canção da Sereia', icon: '🎵', cost: { 'ABYSSAL': 2 }, level: 1, type: 'atk', range: 3, tags: ['ABYSSAL'], desc: 'Atrai o inimigo 1 casa para perto e aplica Encantar (Atordoado).', effect: async (game, caster, target) => { if (!target) return false; target.status = 'stun'; let path = Hex.getNeighbors(target.q, target.r).sort((a, b) => Hex.distance(a, caster) - Hex.distance(b, caster)); for (let h of path) { if (game.map.has(`${h.q},${h.r}`) && !game.getUnitAt(h.q, h.r)) { await game.moveUnit(target, h.q, h.r); break; } } showPopup("Encantado!", target, '#ff69b4'); return true; } },
    { id: 'sl_turno_extra', name: 'Pó de Fada', icon: '✨', cost: { 'MYSTIC': 3 }, level: 2, type: 'def', range: 2, tags: ['SILVESTRE'], desc: 'Zera o cooldown de um aliado, permitindo que ele ande e ataque novamente.', effect: async (game, caster, target) => { if (!target || target === caster || target.faction !== 1) return false; target.hasAttacked = false; target.mp = target.maxMp; showPopup("Turno Extra!", target, '#f1c40f'); return true; } },
    { id: 'sl_caldeirao', name: 'Caldeirão Sombrio', icon: '🍲', cost: { 'UMBRAL': 2 }, level: 2, type: 'def', range: 1, tags: ['VENOM'], desc: 'Sacrifica um aliado adjacente para curar todo o exército em 30 HP.', effect: async (game, caster, target) => { if (!target || target.faction !== 1 || target.isLeader) return false; game.handleDeath(target, caster); game.units.filter(u => u.faction === 1).forEach(u => { u.hp = Math.min(u.maxHp, u.hp + 30); showPopup("+30 HP", u, '#2ecc71'); }); return true; } },
    { id: 'sl_barreira_gelo', name: 'Barreira de Gelo', icon: '🧊', cost: { 'ICE': 3 }, level: 1, type: 'def', range: 0, tags: ['ICE'], desc: 'Cria uma armadura gélida: ganha escudo imediato e cura 15 HP.', effect: async (game, caster) => { caster.status = 'shielded'; caster.hp = Math.min(caster.maxHp, caster.hp + 15); showPopup("Barreira Ativa!", caster, '#00ffff'); return true; } },
    { id: 'sl_vendaval', name: 'Vendaval Rasante', icon: '🌪️', cost: { 'WING': 3 }, level: 1, type: 'atk', range: 2, tags: ['WING'], desc: 'Causa 20 de dano a um alvo e zera o próprio custo de movimento para fugir (Hit & Run).', effect: async (game, caster, target) => { if (!target) return false; target.hp -= 20; caster.hasAttacked = false; caster.mp = caster.maxMp; showPopup("-20 🌪️", target, '#aaa'); showPopup("Vento a Favor!", caster, '#f1c40f'); if (target.hp <= 0) game.handleDeath(target, caster); return true; } }
];

const LEADER_GRIMOIRE_TAGS = { 'mage': ['MYSTIC'], 'orc': ['PRIMAL'], 'necro': ['UMBRAL'], 'paladin': ['CELESTIAL', 'CARAPACE'], 'ranger': ['SILVESTRE', 'STALKER'], 'pyro': ['FIRE'], 'admiral': ['ABYSSAL'], 'vampire': ['UMBRAL', 'STALKER'] };

const LEADERS = [
    { id: 'mage', name: 'Arquimago', emoji: '🧙🏻‍♂️', hp: 60, atk: 12, mp: 4, range: 2, limit: 6, desc: 'Consegue utilizar duas magias por turno.', tags: ['MYSTIC'] },
    { id: 'orc', name: 'Chefe Orc', emoji: '👹', hp: 80, atk: 15, mp: 5, range: 1, limit: 15, desc: 'Líder de Horda (+10% ATK por aliado).', tags: ['PRIMAL'] },
    { id: 'necro', name: 'Necromante', emoji: '💀', hp: 55, atk: 10, mp: 4, range: 2, limit: 8, desc: 'Exército Morto (Domina como Umbral ao matar).', tags: ['UMBRAL'] },
    { id: 'paladin', name: 'Paladina', emoji: '🛡️', hp: 85, atk: 10, mp: 4, range: 1, limit: 6, desc: 'Unidades compradas ganham a tag Celestial. Aliados até 2 hexes curam 2 HP por turno.', tags: ['CELESTIAL', 'CARAPACE'] },
    { id: 'ranger', name: 'Arqueira', emoji: '🏹', hp: 45, atk: 14, mp: 5, range: 3, limit: 6, desc: 'Alcance longo e Doma feras Silvestres facilmente. Silvestres adjacentes a ela recebem +1 de Alcance.', tags: ['SILVESTRE', 'STALKER'], fav: ['FOREST'] },
    { id: 'pyro', name: 'Piromante', emoji: '🔥', hp: 50, atk: 16, mp: 4, range: 2, limit: 6, desc: 'Feras compradas e domadas vêm com queimadura e ganham a tag Ígnea.', tags: ['FIRE'], abilities: ['burn'] },
    { id: 'admiral', name: 'Almirante', emoji: '🏴‍☠️', hp: 65, atk: 13, mp: 5, range: 1, limit: 7, desc: 'Custo de movimento na Água é livre (1). Encontra e doma mais feras Abissais.', tags: ['ABYSSAL'], fav: ['WATER'] },
    { id: 'vampire', name: 'Lord Vampiro', emoji: '🧛🏻‍♂️', hp: 65, atk: 16, mp: 6, range: 1, limit: 7, desc: 'Roubo de vida. Doma feras abatidas transformando em Rastreadores. Fome se não atacar.', tags: ['UMBRAL', 'STALKER'], abilities: ['lifesteal'] },
    { id: 'L_CENTAUR', name: 'Centauro Espectral', emoji: '🏇', hp: 70, maxHp: 70, mp: 6, maxMp: 6, atk: 6, range: 1, tags: ['MYSTIC'], fav: ['PLAINS'], desc: 'Ganha +10% de ATK Base por cada hexágono percorrido antes de atacar no turno.' },
    { id: 'L_ANUBIS', name: 'Anubis', emoji: '🐕‍🦺', hp: 80, maxHp: 80, mp: 3, maxMp: 3, atk: 14, range: 1, tags: ['UMBRAL', 'SAND'], fav: ['DESERT'], desc: 'Sempre que elimina um inimigo, ganha +1 ATK permanentemente (Acumula na run).' },
    { id: 'L_SHAPESHIFTER', name: 'Metamorfo', emoji: '🕵️‍♂️', hp: 85, maxHp: 85, mp: 4, maxMp: 4, atk: 12, range: 1, tags: ['PRIMAL', 'SILVESTRE'], fav: ['FOREST'], desc: 'Alterna posturas sem custo de mana. Urso (+Defesa, Alc:1) ou Falcão (-Defesa, Perfurante, Alc:3).' },
    { id: 'L_EXECUTIONER', name: 'Carrasco', emoji: '🪓', hp: 90, maxHp: 90, mp: 3, maxMp: 3, atk: 18, range: 1, tags: ['STALKER'], fav: ['MOUNTAIN'], desc: 'Possui o ataque especial Execução. Se matar o alvo, recupera a ação e o movimento.' },
    { id: 'L_SUMMONER', name: 'Invocador', emoji: '👨‍🎨', hp: 60, maxHp: 60, mp: 3, maxMp: 3, atk: 8, range: 2, tags: ['MYSTIC'], desc: 'Mestre dos tokens. Usa mana para evocar criaturas como o Dragão Ígneo direto no tabuleiro.' },
    { id: 'L_GENIE', name: 'Gênia', emoji: '🧞‍♀️', hp: 75, maxHp: 75, mp: 5, maxMp: 4, atk: 12, range: 2, tags: ['MYSTIC', 'SAND'], fav: ['DESERT'], desc: 'Possui "Três Desejos". Ao iniciar a fase, escolha entre injetar Ouro, Recursos ou ganhar um Item Épico.' },
    { id: 'L_TROLL', name: 'Troll', emoji: '🧌', hp: 130, maxHp: 130, mp: 3, maxMp: 3, atk: 14, range: 1, tags: ['PRIMAL', 'SILVESTRE'], fav: ['MOUNTAIN', 'FOREST'], desc: 'O Tanque Absoluto. Recupera 15% do HP se passar o turno sem atacar em Montanhas/Florestas.' },
    { id: 'L_SIREN', name: 'Sereia', emoji: '🧜🏻‍♀️', hp: 70, maxHp: 70, mp: 3, maxMp: 3, atk: 10, range: 2, tags: ['ABYSSAL', 'MYSTIC'], fav: ['WATER'], desc: 'Usa a Canção da Sereia para puxar inimigos para perto e atordoá-los.' },
    { id: 'L_FAIRY', name: 'Fada', emoji: '🧚🏻‍♀️', hp: 50, maxHp: 50, mp: 5, maxMp: 5, atk: 6, range: 2, tags: ['MYSTIC', 'SILVESTRE'], fav: ['FOREST'], desc: 'Maga de Suporte. Suas magias curam aliados em área ou concedem turnos extras.' },
    { id: 'L_WITCH', name: 'Bruxa', emoji: '🧙🏼‍♀️', hp: 65, maxHp: 65, mp: 3, maxMp: 3, atk: 12, range: 2, tags: ['VENOM', 'UMBRAL'], fav: ['FOREST'], desc: 'Alquimista. Pode sacrificar um aliado com a magia Caldeirão para curar toda a equipe massivamente.' },
    { id: 'L_BARBARIAN', name: 'Rei Bárbaro', emoji: '🤴', hp: 80, maxHp: 80, mp: 4, maxMp: 4, atk: 16, range: 1, tags: ['PRIMAL', 'ICE'], fav: ['SNOW'], desc: 'Fúria Imortal: Quanto mais HP perder, mais forte ele fica.' },
    { id: 'L_TREX', name: 'T-Rex', emoji: '🦖', hp: 150, maxHp: 150, mp: 3, maxMp: 2, atk: 25, range: 1, tags: ['PRIMAL'], fav: ['DIRT'], desc: 'Kaiju. Bate em todos à frente. A cada passo, esmaga florestas e vilas, tornando-as planícies.' },
    { id: 'L_ICE_QUEEN', name: 'Rainha do Gelo', emoji: '👸🏼', hp: 75, maxHp: 75, mp: 3, maxMp: 3, atk: 12, range: 2, tags: ['ICE'], fav: ['SNOW'], filter: 'hue-rotate(180deg)', abilities: ['frost_armor', 'freeze'], desc: 'Magia glacial. Inimigos que a atacam corpo-a-corpo sofrem Congelamento (Chilled) instantâneo.' },
    { id: 'L_HARPY', name: 'Matriarca Harpia', emoji: '🦅', hp: 65, maxHp: 65, mp: 5, maxMp: 5, atk: 14, range: 1, tags: ['WING'], fav: ['MOUNTAIN'], filter: 'saturate(150%)', abilities: ['flying', 'dodge'], desc: 'Senhora dos ventos. Ignora custos de terreno pesado (sempre move por 1 MP) e possui esquiva natural alta.' }
];

const FACTIONS = { WILD: { id: 0 }, PLAYER: { id: 1 }, AI: { id: 2 } };

const ABILITY_DESCRIPTIONS = {
    dodge: 'Esquiva: 30% chance de ignorar dano.',
    lifesteal: 'Roubo de Vida: Cura 80% do dano causado.',
    poison: 'Veneno: 30% chance de envenenar.',
    stun: 'Atordoamento: 25% chance de atordoar.',
    bind: 'Amarrar: Zera o MP do alvo no próximo turno.',
    burn: 'Queimadura: Causa 10 de dano verdadeiro após o golpe.',
    pierce: 'Perfuração: Ignora a Defesa de terrenos.',
    counter: 'Contra-ataque Letal: Ao ser atacada, revida com 20% mais dano.',
    freeze: 'Congelamento: 25% chance de atordoar e causar 5 de dano puro.',
    leadership: 'Liderança: Aliados ao redor ganham +2 ATK e +20% DEF.',
    electric: 'Eletricidade: Rebate para inimigos adjacentes (50% Dano).',
    hit_run: 'Bater e Correr: Permite mover-se após o ataque.',
    swift: 'Ataque Rápido: O alvo não contra-ataca o golpe.',
    crystal_skin: 'Pele de Cristal: +40% de Defesa base e Imunidade a status.',
    corte_amplo: 'Corte Amplo: Causa 50% de dano aos inimigos adjacentes.',
    carapace: 'Carapaça: Reflete 20% do dano.',
    flying: 'Voo: Ignora o custo de terrenos difíceis. Move-se por 1 MP em qualquer lugar.',
    frost_armor: 'Gelo Retributivo: Inimigos que atacarem a 1 casa de distância sofrem Congelamento.',
};

const EVOS = { 'Rato': ['Rato Alfa', 'Rato Rei'], 'Pássaro': ['Falcão', 'Fênix'], 'Tartaruga': ['Tartaruga Alfa', 'Dinossauro Escudo'], 'Coelho': ['Coelho Alfa', 'Canguru Boxeador'], 'Cavalo': ['Cavalo Alfa', 'Unicórnio Místico'], 'Morcego': ['Vampiro Menor', 'Rei Morcego'], 'Cobra': ['Naja', 'Basilisco'], 'Escorpião': ['Escorpião Rei', 'Imperador do Deserto'], 'Lobo': ['Lobo Alfa', 'Lobo Fenrir'], 'Javali': ['Javali Alfa', 'Rinoceronte'], 'Urso': ['Urso Alfa', 'Panda Místico'], 'Elefante': ['Mamute', 'Mamute Obelisco'], 'Leão Selvagem': ['Príncipe Leão', 'Rei Leão'], 'Aranha Gigante': ['Aranha Alfa', 'Rainha Aranha'], 'Tigre': ['Tigre Branco', 'Dente-de-Sabre'], 'Golem de Pedra': ['Golem de Pedra Alfa', 'Titã de Pedra'], 'Crocodilo': ['Crocodilo Alfa', 'Espinossauro'], 'Tubarão': ['Tubarão Branco', 'Megalodon'], 'Kraken': ['Kraken Ancião', 'Cthulhu'], 'Caranguejo Blindado': ['Caranguejo Gigante', 'Rei Caranguejo'], 'Enguia Elétrica': ['Enguia Alfa', 'Dragão do Mar'], 'Bode da Neve': ['Bode Alfa', 'Carneiro de Batalha'], 'Yeti Atirador': ['Yeti Congelante', 'Pé-Grande'], 'Lobo do Inverno': ['Lobo Gélido', 'Fenrir de Gelo'], 'Macaco': ['Gorila', 'Gorila Rei'], 'Raposa': ['Raposa Ancestral', 'Raposa de Nove Caudas'], 'Pinguim': ['Pinguim Alfa', 'Pinguim Imperador'], 'Sapo': ['Sapo Venenoso', 'Sapo-Boi Gigante'] };

const BEASTS = {
    LAND: [
        { e: '🐭', name: 'Rato', hp: 20, atk: 5, mp: 5, range: 1, abilities: [], minLevel: 1, filter: 'none', tags: ['STALKER', 'SILVESTRE'], fav: ['PLAINS'] }, { e: '🐦', name: 'Pássaro', hp: 30, atk: 9, mp: 5, range: 1, abilities: [], minLevel: 1, filter: 'none', tags: ['WING', 'SILVESTRE'], fav: ['FOREST'] }, { e: '🐢', name: 'Tartaruga', hp: 70, atk: 6, mp: 2, range: 1, abilities: [], minLevel: 1, filter: 'none', tags: ['PRIMAL', 'ROCK'], fav: ['WATER', 'PLAINS'] }, { e: '🐇', name: 'Coelho', hp: 25, atk: 4, mp: 6, range: 1, abilities: ['swift'], minLevel: 1, filter: 'none', tags: ['SILVESTRE'], fav: ['PLAINS'] }, { e: '🐴', name: 'Cavalo', hp: 45, atk: 7, mp: 6, range: 1, abilities: ['hit_run'], minLevel: 1, filter: 'none', tags: ['ROCK'], fav: ['PLAINS'] }, { e: '🦇', name: 'Morcego', hp: 25, atk: 8, mp: 4, range: 1, abilities: ['lifesteal'], minLevel: 1, filter: 'none', tags: ['WING', 'UMBRAL'], fav: ['FOREST'] }, { e: '🐍', name: 'Cobra', hp: 25, atk: 10, mp: 3, range: 1, abilities: ['poison'], minLevel: 1, filter: 'none', tags: ['VENOM', 'SAND'], fav: ['DESERT'] }, { e: '🦂', name: 'Escorpião', hp: 30, atk: 11, mp: 3, range: 1, abilities: ['poison'], minLevel: 1, filter: 'none', tags: ['VENOM', 'SAND', 'CARAPACE'], fav: ['DESERT'] }, { e: '🐒', name: 'Macaco', hp: 35, atk: 10, mp: 4, range: 1, abilities: ['dodge'], minLevel: 1, filter: 'none', tags: ['SILVESTRE', 'PRIMAL'], fav: ['FOREST'] }, { e: '🦊', name: 'Raposa', hp: 25, atk: 12, mp: 5, range: 1, abilities: ['swift'], minLevel: 1, filter: 'none', tags: ['SILVESTRE', 'MYSTIC'], fav: ['FOREST'] }, { e: '🐺', name: 'Lobo', hp: 35, atk: 12, mp: 4, range: 1, abilities: [], minLevel: 2, filter: 'none', tags: ['STALKER', 'ICE'], fav: ['SNOW'] }, { e: '🐗', name: 'Javali', hp: 50, atk: 8, mp: 3, range: 1, abilities: [], minLevel: 2, filter: 'none', tags: ['STALKER', 'ROCK'], fav: ['PLAINS'] }, { e: '🐻', name: 'Urso', hp: 65, atk: 15, mp: 3, range: 1, abilities: ['stun'], minLevel: 2, filter: 'none', tags: ['MYSTIC', 'SILVESTRE'], fav: ['FOREST'] }, { e: '🐘', name: 'Elefante', hp: 90, atk: 12, mp: 2, range: 1, abilities: [], minLevel: 3, filter: 'none', tags: ['PRIMAL', 'SAND'], fav: ['DESERT'] }, { e: '🦁', name: 'Leão Selvagem', hp: 80, atk: 18, mp: 4, range: 1, abilities: ['leadership'], minLevel: 2, filter: 'none', tags: ['STALKER', 'SAND'], fav: ['DESERT'] }, { e: '🕷️', name: 'Aranha Gigante', hp: 40, atk: 14, mp: 4, range: 1, abilities: ['poison'], minLevel: 2, filter: 'none', tags: ['VENOM', 'UMBRAL'], fav: ['FOREST'] }, { e: '🐯', name: 'Tigre', hp: 55, atk: 16, mp: 5, range: 1, abilities: ['dodge'], minLevel: 3, filter: 'none', tags: ['STALKER', 'SILVESTRE'], fav: ['FOREST'] }, { e: '🪨', name: 'Golem de Pedra', hp: 100, atk: 10, mp: 2, range: 1, abilities: ['pierce'], minLevel: 4, filter: 'none', tags: ['ROCK', 'CARAPACE'], fav: ['MOUNTAIN'] }
    ],
    WATER: [{ e: '🐊', name: 'Crocodilo', hp: 55, atk: 14, mp: 3, range: 1, abilities: [], minLevel: 2, filter: 'none', tags: ['PRIMAL', 'ABYSSAL'], fav: ['WATER'] }, { e: '🦈', name: 'Tubarão', hp: 45, atk: 18, mp: 4, range: 1, abilities: ['lifesteal'], minLevel: 2, filter: 'none', tags: ['STALKER', 'ABYSSAL'], fav: ['WATER'] }, { e: '🦑', name: 'Kraken', hp: 75, atk: 12, mp: 2, range: 1, abilities: ['bind'], minLevel: 3, filter: 'none', tags: ['MYSTIC', 'ABYSSAL'], fav: ['WATER'] }, { e: '🦀', name: 'Caranguejo Blindado', hp: 65, atk: 12, mp: 2, range: 1, abilities: ['counter'], minLevel: 2, filter: 'none', tags: ['CARAPACE', 'ABYSSAL'], fav: ['WATER'] }, { e: '🐍', name: 'Enguia Elétrica', hp: 35, atk: 15, mp: 4, range: 1, abilities: ['electric'], minLevel: 3, filter: 'hue-rotate(200deg)', tags: ['MYSTIC', 'ABYSSAL'], fav: ['WATER'] }, { e: '🐸', name: 'Sapo', hp: 25, atk: 9, mp: 3, range: 1, abilities: ['poison'], minLevel: 1, filter: 'none', tags: ['VENOM', 'ABYSSAL'], fav: ['WATER'] }],
    SNOW: [{ e: '🐐', name: 'Bode da Neve', hp: 40, atk: 9, mp: 4, range: 2, abilities: [], minLevel: 1, filter: 'none', tags: ['ROCK', 'ICE'], fav: ['MOUNTAIN', 'SNOW'] }, { e: '☃️', name: 'Yeti Atirador', hp: 45, atk: 11, mp: 2, range: 2, abilities: [], minLevel: 2, filter: 'none', tags: ['MYSTIC', 'ICE'], fav: ['SNOW'] }, { e: '🐺', name: 'Lobo do Inverno', hp: 50, atk: 14, mp: 4, range: 1, abilities: ['freeze'], minLevel: 3, filter: 'brightness(200%) grayscale(100%)', tags: ['STALKER', 'ICE'], fav: ['SNOW'] }, { e: '🐧', name: 'Pinguim', hp: 30, atk: 8, mp: 4, range: 1, abilities: [], minLevel: 1, filter: 'none', tags: ['ABYSSAL', 'ICE'], fav: ['WATER', 'SNOW'] }],
    BOSSES: [{ e: '🦁', name: 'Rei Leão', hp: 80, atk: 18, mp: 4, range: 1, abilities: ['leadership'], minLevel: 1, maxLevel: 1, filter: 'none', tags: ['STALKER', 'SAND'], fav: ['DESERT'] }, { e: '🦍', name: 'Gorila Rei', hp: 120, atk: 22, mp: 3, range: 1, abilities: ['stun'], minLevel: 2, maxLevel: 2, filter: 'none', tags: ['PRIMAL', 'SILVESTRE'], fav: ['FOREST'] }, { e: '🦣', name: 'Mamute Obelisco', hp: 180, atk: 30, mp: 2, range: 1, abilities: [], minLevel: 3, maxLevel: 3, filter: 'none', tags: ['PRIMAL', 'ICE'], fav: ['SNOW'] }, { e: '🦅', name: 'Quimera', hp: 140, atk: 25, mp: 5, range: 2, abilities: ['burn'], minLevel: 4, maxLevel: 5, filter: 'hue-rotate(45deg) saturate(200%)', tags: ['WING', 'FIRE'], fav: ['PLAINS'] }, { e: '👹', name: 'Titã de Gelo', hp: 200, atk: 28, mp: 2, range: 1, abilities: ['freeze'], minLevel: 6, maxLevel: 99, filter: 'hue-rotate(180deg) brightness(120%)', tags: ['PRIMAL', 'ICE'], fav: ['SNOW'] }]
};
const ALL_BEASTS = [...BEASTS.LAND, ...BEASTS.WATER, ...BEASTS.SNOW, ...BEASTS.BOSSES];

const ARTIFACTS = [
    { id: 'art_hp', name: 'Cálice Vital', icon: '🍷', desc: '+15 HP Máx (Tropas).', cost: 15, rarity: 'rare', color: 'var(--rarity-rare)' },
    { id: 'art_atk', name: 'Lâmina de Sangue', icon: '🗡️', desc: '+8 Ataque (Tropas).', cost: 20, rarity: 'epic', color: 'var(--rarity-epic)' },
    { id: 'art_move', name: 'Botas de Hermes', icon: '🥾', desc: '+1 Movimento pro Herói.', cost: 15, rarity: 'rare', color: 'var(--rarity-rare)' },
    { id: 'art_tame', name: 'Anel do Domador', icon: '💍', desc: '+20% chance de Domar.', cost: 18, rarity: 'epic', color: 'var(--rarity-epic)' },
    { id: 'art_gold', name: 'Moeda Real', icon: '👑', desc: 'Saquear Vilas = ouro em dobro.', cost: 18, rarity: 'epic', color: 'var(--rarity-epic)' },
    { id: 'art_shield', name: 'Escudo de Aegis', icon: '🛡️', desc: 'Reduz dano recebido em 15%.', cost: 18, rarity: 'epic', color: 'var(--rarity-epic)' },
    { id: 'art_crown', name: 'Coroa da Liderança', icon: '⚜️', desc: 'Limite do exército +1.', cost: 22, rarity: 'legendary', color: 'var(--rarity-legendary)' },
    { id: 'art_hourglass', name: 'Ampulheta', icon: '⏳', desc: 'Herói cura 5 HP/turno.', cost: 20, rarity: 'epic', color: 'var(--rarity-epic)' },
    { id: 'art_wind', name: 'Capa do Vento', icon: '💨', desc: '+25% Esquiva (Tropas).', cost: 20, rarity: 'epic', color: 'var(--rarity-epic)' },
    { id: 'art_armor', name: 'Manopla de Aço', icon: '🧤', desc: '+15% Defesa Base (Tropas).', cost: 18, rarity: 'rare', color: 'var(--rarity-rare)' },
    { id: 'art_crystal', name: 'Cristal de Mana', icon: '🔮', desc: 'Herói ganha +1 Alcance e +5 ATK.', cost: 25, rarity: 'legendary', color: 'var(--rarity-legendary)' },
    { id: 'art_blood', name: 'Colar Vampírico', icon: '🩸', desc: 'Tropas ganham +20% Roubo de Vida.', cost: 22, rarity: 'epic', color: 'var(--rarity-epic)' },
    { id: 'art_umbral_seal', name: 'Selo do Umbral', icon: '👁️‍🗨️', desc: 'Todas as suas feras ganham a tag Umbral.', cost: 22, rarity: 'epic', color: 'var(--rarity-epic)' },
    { id: 'art_celestial_seal', name: 'Selo Celestial', icon: '👼', desc: 'Todas as suas feras ganham a tag Celestial.', cost: 22, rarity: 'epic', color: 'var(--rarity-epic)' },
    { id: 'art_wild_call', name: 'Chamado Selvagem', icon: '📯', desc: 'Aliados ganham +10 XP no fim da batalha.', cost: 25, rarity: 'legendary', color: 'var(--rarity-legendary)' },
    { id: 'art_omega', name: 'Coração do Infinito', icon: '🌌', desc: '+20 HP, +5 ATK e +1 Limite de Exército.', cost: 999, rarity: 'legendary', color: '#ff00ff' }
];

const ITEMS = {
    'SWORD': { icon: '🗡️', name: 'Espada', desc: '+3 ATK (Multiplica por Nível).', type: 'equip', onEquip: (u, lvl) => { u.atk += 3 * lvl; }, onUnequip: (u, lvl) => { u.atk -= 3 * lvl; } },
    'SHIELD': { icon: '🛡️', name: 'Escudo', desc: '+15 HP Máx (Multiplica por Nível).', type: 'equip', onEquip: (u, lvl) => { u.maxHp += 15 * lvl; u.hp += 15 * lvl; }, onUnequip: (u, lvl) => { u.maxHp -= 15 * lvl; u.hp = Math.min(u.hp, u.maxHp); } },
    'BOW': { icon: '🏹', name: 'Arco', desc: '+1 Alcance.', type: 'equip', onEquip: (u, lvl) => { u.range += 1; }, onUnequip: (u, lvl) => { u.range -= 1; } },
    'BOOTS': { icon: '🥾', name: 'Botas', desc: '+1 Movimentação.', type: 'equip', onEquip: (u, lvl) => { u.maxMp += 1; u.mp += 1; }, onUnequip: (u, lvl) => { u.maxMp -= 1; u.mp = Math.min(u.mp, u.maxMp); } },
    'APPLE': { icon: '🍎', name: 'Maçã Divina', desc: '+10 HP Máx.', type: 'equip', onEquip: (u, lvl) => { u.maxHp += 10 * lvl; u.hp += 10 * lvl; }, onUnequip: (u, lvl) => { u.maxHp -= 10 * lvl; u.hp = Math.min(u.hp, u.maxHp); } },
    'CROWN_LION': { icon: '🦁', name: 'Juba', desc: 'Liderança.', type: 'equip', onEquip: (u, lvl) => { if (!u.abilities.includes('leadership')) u.abilities.push('leadership'); }, onUnequip: (u, lvl) => { u.abilities = u.abilities.filter(a => a !== 'leadership'); } },
    'EEL_SPARK': { icon: '⚡', name: 'Centelha', desc: 'Eletricidade.', type: 'equip', onEquip: (u, lvl) => { if (!u.abilities.includes('electric')) u.abilities.push('electric'); }, onUnequip: (u, lvl) => { u.abilities = u.abilities.filter(a => a !== 'electric'); } },
    'HORSESHOE': { icon: '🧲', name: 'Ferradura', desc: 'Bater e Correr.', type: 'equip', onEquip: (u, lvl) => { if (!u.abilities.includes('hit_run')) u.abilities.push('hit_run'); }, onUnequip: (u, lvl) => { u.abilities = u.abilities.filter(a => a !== 'hit_run'); } },
    'CARROT': { icon: '🥕', name: 'Cenoura Dourada', desc: 'Ataque Rápido.', type: 'equip', onEquip: (u, lvl) => { if (!u.abilities.includes('swift')) u.abilities.push('swift'); }, onUnequip: (u, lvl) => { u.abilities = u.abilities.filter(a => a !== 'swift'); } },
    'RUSTY_SWORD': { icon: '🗡️', name: 'Espada Enferrujada', desc: '+1 ATK.', type: 'equip', onEquip: (u, lvl) => { u.atk += 1 * lvl; }, onUnequip: (u, lvl) => { u.atk -= 1 * lvl; } },
    'WOODEN_SHIELD': { icon: '🛡️', name: 'Escudo de Madeira', desc: '+5 HP Máx.', type: 'equip', onEquip: (u, lvl) => { u.maxHp += 5 * lvl; u.hp += 5 * lvl; }, onUnequip: (u, lvl) => { u.maxHp -= 5 * lvl; u.hp = Math.min(u.hp, u.maxHp); } },
    'BANDAGE': { icon: '🩹', name: 'Bandagem', desc: 'Cura 15 HP.', type: 'instant', f: async (u, g) => { u.hp = Math.min(u.maxHp, u.hp + 15); return true; } },
    'MEAT': { icon: '🍖', name: 'Carne Curada', desc: 'Cura 25 HP.', type: 'instant', f: async (u, g) => { u.hp = Math.min(u.maxHp, u.hp + 25); return true; } },
    'MAGIC': { icon: '🔮', name: 'Pedra Mágica', desc: 'Aprende habilidade aleatória.', type: 'instant', f: async (u, g) => { let k = Object.keys(ABILITY_DESCRIPTIONS); let res = await window.learnAbility(u, k[Math.floor(Math.random() * k.length)]); return res; } },
    'SCROLL': { icon: '📜', name: 'Pergaminho', desc: 'Ganha +100 XP.', type: 'instant', f: async (u, g) => { u.addXp(100); return true; } },
    'COIN': { icon: '🪙', name: 'Moedas', desc: 'Você encontrou 2 de Ouro!', type: 'instant', f: async (u, g) => { if (u.faction === 1) { g.gold += 2; return true; } return false; } },
    'GEM': { icon: '💎', name: 'Gema', desc: 'Você encontrou 5 de Ouro!', type: 'instant', f: async (u, g) => { if (u.faction === 1) { g.gold += 5; return true; } return false; } },
    'KEY': { icon: '🗝️', name: 'Chave', desc: 'Abre Baús.', type: 'instant', f: async (u, g) => { if (u.faction === 1) { g.hasKey = true; return true; } return false; } },
    'CHEST': { icon: '🪎', name: 'Baú', desc: 'Encontrou +8 Ouro.', type: 'instant', f: async (u, g) => { if (u.faction === 1 && g.hasKey) { g.hasKey = false; g.gold += 8; return true; } return false; } },
    'EGG': { icon: '🪺', name: 'Ovo', desc: 'Ovo de Monstro.', type: 'instant', f: async (u, g) => { if (u.faction === 1) { g.hasEgg = true; return true; } return false; } },
    'POTION': { icon: '🧪', name: 'Poção Menor', desc: 'Cura 30 HP.', type: 'instant', f: async (u, g) => { u.hp = Math.min(u.maxHp, u.hp + 30); return true; } }
};

const NODE_TYPES = {
    BATTLE: { icon: '⚔️', name: 'Batalha', color: '#4a9edd' },
    ELITE: { icon: '👹', name: 'Elite', color: '#e74c3c' },
    EVENT: { icon: '❓', name: 'Evento', color: '#9b59b6' },
    TREASURE: { icon: '💎', name: 'Tesouro', color: '#f1c40f' },
    SHOP: { icon: '💰', name: 'Mercador', color: '#2ecc71' },
    BOSS: { icon: '👑', name: 'Chefe', color: '#c9a227' },
    LAB: { icon: '🧬', name: 'Laboratório', color: '#1abc9c' }
};

const EVENTS = [
    { title: 'A Forja Sombria', icon: '🔥', desc: 'Uma forja que queima com chamas azuis e gélidas. "O metal exige sacrifício."', choices: [{ text: 'Oferenda de Sangue', desc: 'Líder perde 15% HP Máx. Ganhe item Épico.', req: () => true, action: async () => { let l = deployedRoster.find(u => u.isLeader); if (l) { l.maxHp = Math.max(1, Math.floor(l.maxHp * 0.85)); l.hp = Math.min(l.hp, l.maxHp); } await window.giveRandomArtifact('epic'); } }, { text: 'O Teste do Fogo', desc: 'Time inicia com -25% de HP. Ganhe item Raro.', req: () => true, action: async () => { deployedRoster.forEach(u => u.hp = Math.max(1, Math.floor(u.maxHp * 0.75))); await window.giveRandomArtifact('rare'); } }, { text: 'Ignorar a Forja', desc: 'Siga em frente.', req: () => true, action: async () => { } }] },
    { title: 'A Anomalia no Tabuleiro', icon: '🌌', desc: 'O terreno está distorcido. Atravessar essa zona altera as unidades.', choices: [{ text: 'Estudar Anomalia (50 Ouro)', desc: 'Uma unidade ganha +2 Movimento.', req: () => game.gold >= 50, action: async () => { game.gold -= 50; let u = await window.promptSelectUnit("Quem ganhará +2 Mov?", deployedRoster); if (u) { u.maxMp += 2; u.mp += 2; } } }, { text: 'Absorver a Energia', desc: 'Ganhe +5 ATK e perca 1 Mov.', req: () => true, action: async () => { let u = await window.promptSelectUnit("Quem absorverá a energia?", deployedRoster); if (u) { u.atk += 5; u.maxMp = Math.max(1, u.maxMp - 1); u.mp = u.maxMp; } } }, { text: 'Mapear um Desvio', desc: 'O próximo mapa não terá Vilas.', req: () => true, action: async () => { game.eventFlags.noVillages = true; } }] },
    { title: 'O Mercenário Veterano', icon: '⚔️', desc: 'Um guerreiro veterano afia a espada.', choices: [{ text: 'Comprar Herança (40 Ouro)', desc: 'Compre um Artefato Lendário.', req: () => game.gold >= 40, action: async () => { game.gold -= 40; await window.giveRandomArtifact('legendary'); } }, { text: 'Treinamento (20 Ouro)', desc: 'Uma unidade ganha 200 XP.', req: () => game.gold >= 20, action: async () => { game.gold -= 20; let u = await window.promptSelectUnit("Quem vai treinar?", deployedRoster); if (u) u.addXp(200); } }, { text: 'Tentar Roubar', desc: 'Inicia uma batalha de Chefe.', req: () => true, action: async () => { game.eventFlags.veteranBoss = true; } }, { text: 'Ignorar', desc: 'Siga em frente.', req: () => true, action: async () => { } }] },
    { title: 'O Ninho das Serpes', icon: '🥚', desc: 'Um ninho cheio de ovos...', choices: [{ text: 'Roubar um Ovo', desc: 'Ganha 1 Cobra e Artefato Raro. A Mãe VAI te emboscar!', req: () => true, action: async () => { let b = BEASTS.LAND.find(x => x.name === 'Cobra'); rosterMemory.push(new Unit({ ...b, q: 0, r: 0, faction: 1, isNew: true })); await window.giveRandomArtifact('rare'); game.eventFlags.serpentAmbush = true; } }, { text: 'Mineração Rápida', desc: 'Ganhe 50 Ouro, duas unidades perdem HP.', req: () => true, action: async () => { game.gold += 50; let u1 = await window.promptSelectUnit("Selecione a 1ª para receber dano:", deployedRoster); let u2 = await window.promptSelectUnit("Selecione a 2ª para receber dano:", deployedRoster.filter(x => x !== u1)); if (u1) u1.hp = Math.max(1, Math.floor(u1.maxHp * 0.7)); if (u2) u2.hp = Math.max(1, Math.floor(u2.maxHp * 0.7)); } }, { text: 'Retirada Silenciosa', desc: 'Esquadrão ganha +30 XP.', req: () => true, action: async () => { deployedRoster.forEach(u => u.addXp(30)); } }] },
    { title: 'Campo Assombrado', icon: '👻', desc: 'Espíritos repetem suas táticas de combate.', choices: [{ text: 'Estudo Macabro (-15% HP)', desc: 'Aprende Corte Amplo.', req: () => deployedRoster.some(u => u.range === 1), action: async () => { let u = await window.promptSelectUnit("Quem aprenderá Corte Amplo?", deployedRoster.filter(x => x.range === 1)); if (u) u.abilities.push('corte_amplo'); deployedRoster.forEach(x => x.hp = Math.max(1, Math.floor(x.maxHp * 0.85))); } }, { text: 'Purificar Terreno (15 Ouro)', desc: 'Receba 2 itens Épicos. Inimigos fracos.', req: () => game.gold >= 15, action: async () => { game.gold -= 15; await window.giveRandomArtifact('epic'); await window.giveRandomArtifact('epic'); game.eventFlags.hauntedCurse = true; } }, { text: 'Marchar às Cegas', desc: 'No próximo combate, suas unidades iniciam espalhadas.', req: () => true, action: async () => { game.eventFlags.scatterUnits = true; } }] },
];

// ==========================================
// ESTRUTURAS DO REINO
// ==========================================
const BUILDINGS = {
    CASTLE: { id: 'CASTLE', name: 'Castelo Real', icon: '🏰', cost: {}, desc: 'O coração do seu Reino. Não pode ser destruído.', terrains: ['PLAINS', 'FOREST', 'MOUNTAIN', 'WATER', 'SNOW', 'DESERT'] },
    STABLE: { id: 'STABLE', name: 'Estábulo', icon: '🐎', cost: { wood: 0, stone: 0 }, desc: 'O Mercador sempre venderá um Cavalo extra.', terrains: ['PLAINS', 'DESERT', 'SNOW'] },
    CHURCH: { id: 'CHURCH', name: 'Igreja', icon: '⛪', cost: { stone: 7, sand: 5, wood: 6 }, desc: 'Recebe uma pomba Celestial imediatamente.', terrains: ['PLAINS', 'MOUNTAIN', 'SNOW'] },
    MINE: { id: 'MINE', name: 'Mina', icon: '⛏️', cost: { wood: 5, stone: 2 }, desc: 'Gera +3 Pedra e +1 Ouro ao vencer batalhas.', terrains: ['MOUNTAIN'] },
    LUMBERMILL: { id: 'LUMBERMILL', name: 'Madeireira', icon: '🪓', cost: { stone: 5, wood: 2 }, desc: 'Gera +3 Madeira ao vencer batalhas.', terrains: ['FOREST'] },
    FISHINGCAMP: { id: 'FISHINGCAMP', name: 'Campo de Pesca', icon: '🎣', cost: { wood: 7 }, desc: 'Gera +3 Escamas ao vencer batalhas.', terrains: ['WATER'] },
    SANDPIT: { id: 'SANDPIT', name: 'Extrator de Areia', icon: '🐪', cost: { wood: 2, stone: 1 }, desc: 'Gera +3 Areia ao vencer batalhas.', terrains: ['DESERT'] },
    PARK: { id: 'PARK', name: 'Parque', icon: '⛲', cost: { stone: 10, sand: 10 }, desc: 'Grande chance de domar feras Nv1 com HP cheio.', terrains: ['PLAINS', 'FOREST', 'DESERT', 'SNOW'] },
    FARM: { id: 'FARM', name: 'Fazenda', icon: '🌾', cost: { wood: 15 }, desc: 'Todas as feras ganham +10 HP Máx.', terrains: ['PLAINS'] },
    TOWN: { id: 'TOWN', name: 'Vila', icon: '🏘️', cost: { wood: 5, stone: 5, sand: 5, scales: 5 }, desc: 'Aumenta o espaço na equipe em +1.', terrains: ['PLAINS', 'FOREST', 'DESERT', 'SNOW'] },
    BESTIARY: { id: 'BESTIARY', name: 'Bestiário', icon: '📖', cost: { wood: 0, scales: 0 }, desc: 'Aumenta a chance global de domar feras.', terrains: ['PLAINS', 'FOREST', 'SNOW'] },
    MARKET: { id: 'MARKET', name: 'Mercado', icon: '⚖️', cost: { wood: 0, stone: 0 }, desc: 'Permite a troca de recursos básicos por ouro e vice-versa.', terrains: ['PLAINS', 'DESERT', 'SNOW'] },
    CRYSTAL_TOWER: { id: 'CRYSTAL_TOWER', name: 'Torre de Cristal', icon: '🔮', cost: { stone: 15, sand: 10 }, desc: 'O líder inicia o 1º turno do combate com +1 de Mana.', terrains: ['MOUNTAIN', 'SNOW'] },
    SHADOW_ALTAR: { id: 'SHADOW_ALTAR', name: 'Altar das Sombras', icon: '🪦', cost: { stone: 0, scales: 0 }, desc: 'Sacrifica feras por recursos (Apenas Líderes Umbrais).', terrains: ['MOUNTAIN', 'DESERT', 'FOREST'] },
    FORGE: { id: 'FORGE', name: 'Forja', icon: '⚒️', cost: { wood: 0, stone: 0 }, desc: 'Forje itens e consumíveis direto para a sua mochila.', terrains: ['MOUNTAIN', 'PLAINS'] },
    BARRACKS: { id: 'BARRACKS', name: 'Quartel', icon: '⛺', cost: { wood: 5, stone: 0 }, desc: 'Recrute feras que compartilham a afinidade do seu Líder.', terrains: ['PLAINS', 'DESERT'] },
    LIBRARY: { id: 'LIBRARY', name: 'Biblioteca', icon: '📚', cost: { wood: 0, sand: 0 }, desc: '[Em Breve] Desbloqueia a Árvore de Habilidades.', terrains: ['PLAINS', 'SNOW'] },
    PORT: { id: 'PORT', name: 'Porto', icon: '⚓', cost: { wood: 0, stone: 0 }, desc: 'Gera +5 Ouro ao vencer batalhas.', terrains: ['WATER'] },
    TRAP_MAKER: {name: 'Armadilheiro', icon: '🪤', desc: 'Produz Redes e Iscas automaticamente a cada turno.', onTurn: (game) => { game.fieldItems.isca++; game.fieldItems.rede++; }}
};
